{% set name = "argon2-cffi-bindings" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: b957f3e6ea4d55d820e40ff76f450952807013d361a65d7f28acc0acbf29229d

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
  host:
    - pip
    - python
    - cffi >=1.0.1  # [py<314]
    - cffi >=2  # [py>=314]
    - setuptools >=77
    - setuptools_scm >=6.2
    - toml
  run:
    - python
    - cffi >=1.0.1  # [py<314]
    - cffi >=2  # [py>=314]

test:
  source_files:
    - tests
  imports:
    - _argon2_cffi_bindings
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/hynek/argon2-cffi-bindings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Low-level Python CFFI Bindings for Argon2
  description: |
    argon2-cffi-bindings provides low-level CFFI bindings to the Argon2
    password hashing algorithm including a vendored version of them.
  doc_url: https://github.com/hynek/argon2-cffi-bindings
  dev_url: https://github.com/hynek/argon2-cffi-bindings

extra:
  recipe-maintainers:
    - stuertz
